#! /usr/bin/env bash

# The contents of these files are all identical; the information is carries by
# the file name which should be in the form <tool>-<version>-<target>. See
# msvc-dispatch for details.
#
src_exe="$(realpath ${BASH_SOURCE[0]})"
src_dir="$(dirname "$src_exe")"

source "$src_dir/msvc-dispatch"
