#! /usr/bin/env bash

# MSVC 14 setup/configuration.
#
# Should set the SDKBIN, VCBIN, INCLUDE, and LIB variables.
#

# SDK
#
SDK="C:\\Program Files (x86)\\Windows Kits\\8.1"
SDKBIN="$SDK\\bin\\x86"

INCLUDE="$SDK\\include\\shared;$SDK\\include\\um;$SDK\\include\\winrt"
LIB="$SDK\\lib\\winv6.3\\um\\x86"

# CRT
#
CRT="C:\\Program Files (x86)\\Windows Kits\\10"
CRTVER="10.0.10150.0"

INCLUDE="$CRT\\include\\$CRTVER\\ucrt;$INCLUDE"
LIB="$CRT\\lib\\$CRTVER\\ucrt\\x86;$LIB"

# VC
#
VC="C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC"
VCBIN="$VC\\bin"

INCLUDE="$VC\\include;$INCLUDE"
LIB="$VC\\lib;$LIB"
