#! /usr/bin/env bash

# file      : msvc-12/msvc-12-32
# copyright : Copyright (c) 2014-2019 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

# MSVC 12 32-bit setup/configuration (note: using 64-to-32 cross-compiler).
#
# Should set the SDKBIN, VCBIN, VCDLL, INCLUDE, and LIB variables.
#
if [ -z "$MSVC_INSTALLDIR" ]; then
  MSVC_INSTALLDIR="Microsoft Visual Studio 12.0"
fi

# SDK
#
SDK="C:\\Program Files (x86)\\Windows Kits\\8.1"
SDKBIN="$SDK\\bin\\x86"

INCLUDE="$SDK\\include\\shared;$SDK\\include\\um;$SDK\\include\\winrt"
LIB="$SDK\\lib\\winv6.3\\um\\x86"

# VC
#
VC="C:\\Program Files (x86)\\$MSVC_INSTALLDIR\\VC"
VCBIN="$VC\\bin\\amd64_x86"
VCDLL="$VC\\bin\\amd64"

INCLUDE="$VC\\include;$INCLUDE"
LIB="$VC\\lib;$LIB"
