#! /usr/bin/env bash

# file      : msvc-11/msvc-11-32
# copyright : Copyright (c) 2014-2019 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

# MSVC 11 32-bit setup/configuration.
#
# Should set the SDKBIN, VCBIN, VCDLL, INCLUDE, and LIB variables.
#
if [ -z "$MSVC_INSTALLDIR" ]; then
  MSVC_INSTALLDIR="Microsoft Visual Studio 11.0"
fi

# SDK
#
SDK="C:\\Program Files (x86)\\Windows Kits\\8.0"
SDKBIN="$SDK\\bin\\x86"

INCLUDE="$SDK\\include\\shared;$SDK\\include\\um;$SDK\\include\\winrt"
LIB="$SDK\\lib\\win8\\um\\x86"

# VC
#
VC="C:\\Program Files (x86)\\$MSVC_INSTALLDIR\\VC"
VCBIN="$VC\\bin"
VCDLL="$VC\\bin"

INCLUDE="$VC\\include;$INCLUDE"
LIB="$VC\\lib;$LIB"
